### ISSUE TITLE
Could you share a instructions

### ISSUE THREAD

**Issue by firaterdem** [theonegis/ganstfm#2]
Thank you for your valuable work. It is different from the deep learning applications that are generally used. So I couldn't figure out how to implement the code. Could you share instructions for the usage of the code? Thanks in advance.

**Comment by bijogeorgephilip** [comment]
@firaterdem I hope you have found out the instructions to run it successfully, could you please share?

**Comment by bijogeorgephilip** [comment]
@firaterdem Can you please share the instructions if you have successfully implemented?
